use_frameworks!

platform :ios, '9.0'

target 'CK_pod_Example' do
  pod 'CK_pod', :path => '../'

  target 'CK_pod_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
